---
- hosts: optima

  vars:
    # prudentia_dir -> is passed in the cmd line
    - root_dir: ..
    - version: develop
    - db_url: postgresql://optima:optima@localhost:5432/optima

  vars_files:
    - "{{prudentia_dir}}/vars/global.yml"
    - ./common_vars.yml

  tasks:
    - include: "{{prudentia_dir}}/tasks/common-setup.yml"


    - include: "{{root_dir}}/components/common.yml"

    - include: "{{root_dir}}/components/db.yml"

    - include: "{{root_dir}}/components/client.yml"

    - include: "{{root_dir}}/components/api.yml"
