- hosts: all
  sudo: yes
  vars:
    - apps: [
       {
          name: staging,
          domain: staging-new.optimamodel.com,
          port: 9000,
          repo: "github.com/optimamodel/optima.git",
          branch: graph_2x_and_fit_better_css
        },
        {
          name: sandbox,
          domain: sandbox.optimamodel.com,
          port: 9001,
          repo: "github.com/optimamodel/optima.git",
          branch: stable_calc
        },
        {
          name: cdc,
          domain: cdc.optimamodel.com,
          port: 9002,
          repo: "github.com/optimamodel/optima.git",
          branch: cdc_demo
        },
        {
          name: newdb,
          domain: newdb.optimamodel.com,
          port: 9003,
          repo: "github.com/optimamodel/optima.git",
          branch: db-refactor
        }
      ]
    - user: optima
  #pre_tasks:
  #  - apt: update_cache=yes
  roles:
    - {
        role: user
      }
    - {
        role: anaconda
    }
    - {
        role: optima,
        app: "{{ apps.0 }}",
        tags: ["staging"]
      }
    - {
        role: optima,
        app: "{{ apps.1 }}",
        tags: ["sandbox"]
      }
    - {
        role: optima,
        app: "{{ apps.2 }}",
        tags: ["cdc_demo"]
      }
    - {
        role: optima,
        app: "{{ apps.3 }}",
        tags: ["newdb"]
      }
    - {
        role: rproxy,
        tags: ["rproxy"]
      }
