- hosts: all
  sudo: yes
  vars:
    - apps: [
        {
          name: sandbox,
          domain: sandbox.optimamodel.com,
          port: 9001,
          repo: "github.com/optimamodel/optima.git",
          branch: develop
        }
      ]
    - user: optima
  #pre_tasks:
  #  - apt: update_cache=yes
  roles:
    - {
        role: user
      }
    - {
        role: optima,
        app: "{{ apps.0 }}"
      }
    - {
        role: rproxy
      }
