- hosts: all
  sudo: yes
  vars:
    - apps: [
       {
          name: staging,
          domain: staging-new.optimamodel.com,
          port: 9000,
          repo: "github.com/optimamodel/optima.git",
          branch: develop-without-graph-fixes
        },
        {
          name: sandbox,
          domain: sandbox.optimamodel.com,
          port: 9001,
          repo: "github.com/optimamodel/optima.git",
          branch: develop
        },
        {
          name: cdc,
          domain: cdc.optimamodel.com,
          port: 9002,
          repo: "github.com/optimamodel/optima.git",
          branch: develop
        }
      ]
    - user: optima
  #pre_tasks:
  #  - apt: update_cache=yes
  roles:
    - {
        role: user
      }
    - {
        role: anaconda
    }
    - {
        role: optima,
        app: "{{ apps.0 }}"
      }
    - {
        role: optima,
        app: "{{ apps.1 }}"
      }
    - {
        role: optima,
        app: "{{ apps.2 }}"
      }
    - {
        role: rproxy
      }
